### ISSUE TITLE
On_incoming_packets is accessing candidates directly

### ISSUE THREAD

**Issue by NielsZeilemaker** [Tribler/dispersy#177]
On_incoming_packets replaces the default Candidate instance with a WalkCandidate if a WalkCandidate is registered at that sock_addr.

The community.get_candidate method seems more appropriate? Why isn't that one used?

**Comment by boudewijn-tribler** [comment]
From what I can see `meta.community.candidates.get(candidate.sock_addr) or self._bootstrap_candidates.get(candidate.sock_addr)` can be replaced with `meta.community.get_candidate(candidate.sock_addr)`

`get_candidate` is probably not used because it didn't exist when this was originally written, and subsequent changes kept this 'style' the same.

**Comment by NielsZeilemaker** [comment]
I was thinking exactly the same, might be a nice addition

**Comment by boudewijn-tribler** [comment]
See #187
