### ISSUE TITLE
Bootstrap server test does not work anymore after n-hop sync

### ISSUE THREAD

**Issue by devos50** [Tribler/dispersy#554]
It seems that our bootstrap server test is broken after merge of n-hop sync (https://github.com/Tribler/dispersy/commit/1e2a70cf8a6dbf1d9e718df8679aee1479c063c2). See https://jenkins.tribler.org/job/Test_BootstrapServers/31812/ and https://jenkins.tribler.org/job/Test_BootstrapServers/31813/).

@qstokkink can you investigate this?

**Comment by devos50** [comment]
I've also tested this on the bbq server and I confirm that the test doesn't work after the merge.

**Comment by devos50** [comment]
@qstokkink also, my market experiment without the n-hop sync works as expected but with n-hop sync, no asks/bids are sent to other nodes :(

**Comment by qstokkink** [comment]
@devos50 Weird, _it works on my machine_<sup>TM</sup>. I'll investigate this today.

EDIT: Oh wait, that test is on SKIP by default.
EDIT2: It seems that backwards compatibility is still a thing, I'll refactor the n-hop-sync to its own `Destination` subclass.
EDIT3: Your experiment not working anymore is a consequence of the peers no longer being able to communicate with the bootstrap servers.
EDIT4: Thankfully, the fix for this is rather small.
