### ISSUE TITLE
Acceptable_global_time is checked when sync is turned off

### ISSUE THREAD

**Issue by NielsZeilemaker** [Tribler/dispersy#79]
Currently, the acceptable_global_time property is checked in then check_full_sync method. 
However, in communities which have sync turned off (searchcommunity), torrent messages which are created by on demand by other peers are dropped as the current global_time is higher than the default range.

**Comment by NielsZeilemaker** [comment]
I just noticed this snippet in the previewcommunity:

``` python
    @property
    def dispersy_acceptable_global_time_range(self):
        # we will accept the full 64 bit global time range
        return 2 ** 64 - self._global_time
```

I could do the same in the searchcommunity, but a parameter makes more sense.

**Comment by boudewijn-tribler** [comment]
We will add a property called `dispersy_enable_sync`.  When this returns False:
- `dispersy_take_step` will always be called with allow_sync = False
- `acceptable_global_time` will return 2 *\* 63 - 1 instead of its previous calculation involving current global time, mean neighborhood global time, and `dispersy_acceptable_global_time_range`.

**Comment by NielsZeilemaker** [comment]
Great

**Comment by boudewijn-tribler** [comment]
See #89.

Only difference with previous comment is that the property is called `dispersy_enable_bloom_filter_sync` to keep in line with the other property names.

**Comment by boudewijn-tribler** [comment]
See https://github.com/Tribler/tribler/issues/217.

Preview- and SeachCommunity are using this new property.  Any other communities where this should be applied?
